-- Your SQL goes here
CREATE TABLE api_keys (
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `key` VARCHAR(255) NOT NULL,
    user_id INT UNSIGNED NOT NULL REFERENCES users(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMP,
    updated_at TIMESTAMP
);
